- name: THIS IS TEST A PLAYBOOK
  hosts: testhost
  tasks:
    - name: Add Banner
      cisco.ios.ios_banner:
        banner: login
        text: |
          ASDM THIS IS TEST BANNERR
        state: present
    - name: Add loopback
      cisco.ios.ios_interfaces:
        config:
          - name: Loopback4
            description: L4 Configured by Ansible
        state: merged